### ISSUE TITLE
Question:  Docker compose files (.yml and .overide.yml) files are diff than the readme

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [praetorian-inc/purple-team-attack-automation#2]
## Steps to reproduce
When pulling the repository there are two docker-compose files.
1. docker-compose.yml
``` 
version: '3'
services:
  ms:
    image: metasploitframework/metasploit-framework:latest
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    links:
      - db
    ports:
      - 4444:4444
    volumes:
      - $HOME/.msf4:/home/msf/.msf4

  db:
    image: postgres:10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
````
2. docker-compose.override.yml
```
version: '3'

services:
  ms:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUNDLER_ARGS: --jobs=8
    image: metasploit:dev
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf_dev?pool=200&timeout=5
    volumes:
      - .:/usr/src/metasploit-framework
```
**The README info (which seems to be a mix of both):**
```
version: '3'
services:
  ms:
    environment:
      # example of setting LHOST
      LHOST: [Your system's IP address]
    # example of adding more ports
    ports:
      - 8080:8080
      - 443:443
```
Which file should i use to add the LHOST to?
Also the ports component is in the standard docker-compose.yml file.  Do i need to add ports there or add ports to the .override.yml file?

Im trying to be a clear as possible, lol, but if its your not understanding, let me know.

thank you!
